# Generated by Django 4.0.4 on 2022-06-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cat',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='cod',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
