# Generated by Django 4.0.4 on 2022-06-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_users_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='correo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
