# Generated by Django 4.0.5 on 2022-06-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='fundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='formularioDonaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=14)),
                ('monto', models.IntegerField(max_length=75)),
                ('detalle', models.TextField()),
                ('fundacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.fundation')),
            ],
        ),
    ]
