# Generated by Django 4.0.5 on 2022-06-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_fundation_formulariodonaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fundation',
            new_name='fundacion',
        ),
        migrations.RenameField(
            model_name='formulariodonaciones',
            old_name='fundacion',
            new_name='nombreFundacion',
        ),
        migrations.RenameField(
            model_name='fundacion',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='formulariodonaciones',
            name='monto',
            field=models.IntegerField(),
        ),
    ]
