# Generated by Django 4.0.5 on 2022-06-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_rename_fundation_fundacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodonaciones',
            name='detalle',
            field=models.CharField(max_length=200),
        ),
    ]
