# Generated by Django 4.0.5 on 2022-06-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_formulariodonaciones_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariodonaciones',
            name='detalle',
        ),
    ]
